# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to remote repo

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Scivision.Py
        run: |
          pip install .
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
      - name: Build
        working-directory: frontend
        run: npm run build && cp ./dist/index.html ./dist/404.html ./dist/CNAME
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: "./frontend/dist"
          destination-github-username: "alan-turing-institute"
          destination-repository-name: "scivision-website-beta"
          user-email: ifenton@turing.ac.uk
          target-branch: main
